Numpy is a general purpose array processing package.It provides a high performance multi dimensional array object and tools for working with these arrays.The main usage of arrays is because they are very fast , so these are mainly used in EDA and ML algorithms.

In [ ]:
pip install numpy #to install numpy package

In [1]:
import numpy as np #to import numpy package

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [ ]:
arr.reshape()

In [28]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
np_arr = np.array([my_lst1,my_lst2,my_lst3])
np_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
np_arr.shape

(3, 5)

In [10]:
np_arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
arr1=np_arr.reshape(1,15)

Indexing is nothing but accessing the elements of each array.Indexing starts from 0 in numpy array.

In [23]:
arr1[3]

4

In [31]:
np_arr[0:2,2:]# Accessing the required elements only using indexing

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [33]:
arr2 =  np.arange(0,10)#It will create an random array with elements between 0 to 10
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2 =  np.arange(0,10,step=2)#It will create an random array with elements between 0 to 10 with step value 2
arr2

array([0, 2, 4, 6, 8])

In [46]:
np.linspace(1,10,50)#This will create an array with elements between 1 and 10 and equally spaced as 50 elements

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [49]:
arr2[2:] = 10#This is called as broadcasting where it replaces all the elements from the provided index number with the given value
arr2

array([ 0,  2, 10, 10, 10])

In [50]:
arr2<3

array([ True,  True, False, False, False])

In [51]:
arr2*2

array([ 0,  4, 20, 20, 20])

In [52]:
arr2+2

array([ 2,  4, 12, 12, 12])

In [53]:
arr2[arr2<3]

array([0, 2])

In [58]:
np.arange(2,50,3).reshape(8,2)

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29],
       [32, 35],
       [38, 41],
       [44, 47]])

In [60]:
np.ones(4)#This will create an array with size provided and all elements are ones

array([1., 1., 1., 1.])

In [61]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [63]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
np.random.rand(3,3)#This will generate an array with all the random values wih the size provided and all elements are between 0 and 1
#This is based on random distribution

array([[0.18745942, 0.62545227, 0.84018835],
       [0.58074024, 0.1623223 , 0.98092878],
       [0.5424334 , 0.6161777 , 0.29975973]])

In [84]:
np.random.randn(3,3)#This is based on the standard distribution

array([[ 0.79955791, -1.17629879,  1.073423  ],
       [-0.88013856,  0.47909622, -1.00431305],
       [ 1.60234118,  0.06311415,  0.48606152]])

In [105]:
np.random.random_sample((1,5))#Returns the random values between 0 to 1

array([[0.70924683, 0.35221633, 0.65086194, 0.99240307, 0.31463005]])

In [89]:
np.random.randint(0,100,8)#This will select random 8 elements from 0 to 100

array([47, 43, 77, 25, 41, 65, 32, 90])