### Pandas Tutorial

Pandas is an ope source library high performance easy to use data structures and data analysis tool for pyhton programming language.

In [5]:
import pandas as pd
import numpy as np
from io import StringIO,BytesIO

Dataframe is a kind data structure combination of rows and columns which hold the data of the file.

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Col1','Col2','Col3','Col4'])

In [3]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [4]:
df.to_csv('Test1.csv')

In [5]:
## Accessing the elements
## 1. .loc 2. .iloc

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [6]:
type(df.loc['Row1'])

pandas.core.series.Series

Dataseries is nothing but either one entire column or one entire row of data.

In [9]:
type(df.iloc[0:1,0:1])#As it conists of atleast one row and column so it is an dataframe.

pandas.core.frame.DataFrame

In [10]:
df.iloc[0:3,0:3]

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10

In [11]:
#Convert Datafrmaes to an array
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
#Getting the shape of the array
df.iloc[:,:].values.shape

(5, 4)

In [12]:
#Convert Dataseries to and array
df.loc['Row1'].values

array([0, 1, 2, 3])

In [14]:
#Getting the shape of the array
df.loc['Row1'].values.shape

(4,)

In [15]:
df.isnull().sum()#Provides the sum of all the null values in the column

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [16]:
df['Col1'].value_counts()#Provides the each element count in the provided column

0     1
8     1
4     1
16    1
12    1
Name: Col1, dtype: int64

In [17]:
df['Col1'].unique()#Provides the array of unique values in the particular column

array([ 0,  4,  8, 12, 16])

In [18]:
 df = pd.read_csv('mercedesbenz.csv')#Using read_csv we can read other type of seperators as well with sep = '' as parameter

In [23]:
df.head()#head() provides the data for first 5 rows

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [24]:
df.info()#Get the different details about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [26]:
df.describe()#Provides the indepth details about the dataframe

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [29]:
df['X10'].value_counts()#Gets the unique category counts

0    4153
1      56
Name: X10, dtype: int64

In [32]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [34]:
data = ('col1,col2,col3\n'
           'x,y,1\n'
           'a,b,2\n'
            'c,d,3\n')

In [40]:
print(data)

col1,col2,col3
x,y,1
a,b,2
c,d,3



In [36]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [38]:
df = pd.read_csv(StringIO(data),usecols = lambda x:x.upper() in ['COL1','COL3'])#Read only the specific columns from data
df = pd.read_csv(StringIO(data),usecols = ['COL1','COL3'])#Both are same

In [39]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [42]:
df = pd.read_csv(StringIO(data),dtype=object)

In [45]:
df

col1 col2 col3
0    x    y    1
1    a    b    2
2    c    d    3

In [50]:
df['col1']

0    x
1    a
2    c
Name: col1, dtype: object

In [52]:
df = pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})

In [1]:
data = ('index,a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orange,cow,10')

In [6]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [7]:
pd.read_csv(StringIO(data),index_col=0) #This is used when we are trying to make 0th column as index column of the df

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [10]:
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')

In [12]:
pd.read_csv(StringIO(data),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [13]:
data = 'a,b\n"hello, \\"Bob\\",nice to see you",5'

In [14]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob",nice to see you  5

In [20]:
Data = '{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr.Developer"}]}','{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr.Developer"}]}''
df1=pd.read_json(Data)

SyntaxError: EOL while scanning string literal (<ipython-input-20-02b4768e0071>, line 1)

In [18]:
df1.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr.Developer"}}}'

In [21]:
url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url,match='country',header=0)

In [23]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [ ]:
df_excel = pd.read_excel('Excel path')

All pandas objects are equipped with to_pickle methods which use Python's cPickle module to save data structures to disk
using the pickle format.This is called pickling

Using df.to_pickle and pd.read_pickle we can read the pickle files.